from subprograms.create_schema import CreateSchemaSubprogram
from subprograms.recommend_bets import RecommendBetsSubprogram
from subprograms.etl_fonbet_odds import ETLFonbetOddsSubprogram
from subprograms.etl_line4bet_odds import ETLLine4BetOddsSubprogram
from subprograms.etl_championat_tournaments import ETLChampionatTournamentsSubprogram
